import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { generateSlashCommands } from '../../src/commands/generate-slash-commands';

function makeTmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'gen-slash-test-'));
}

describe('generateSlashCommands - command_name routing', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmpDir();
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('writes command_name skill to parent directory (top-level command)', () => {
    const skillsDir = path.join(__dirname, 'fixtures', 'command-name-skill');
    generateSlashCommands({
      platforms: ['claude-code'],
      global: false,
      includeGlobal: false,
      skillsDir,
      output: tmpDir,
      dryRun: false,
      yes: false,
    });

    // Should be at parent level as harness.md → registers as /harness
    expect(fs.existsSync(path.join(tmpDir, 'harness.md'))).toBe(true);
  });

  it('does not write command_name skill into the namespace subdirectory', () => {
    const skillsDir = path.join(__dirname, 'fixtures', 'command-name-skill');
    generateSlashCommands({
      platforms: ['claude-code'],
      global: false,
      includeGlobal: false,
      skillsDir,
      output: tmpDir,
      dryRun: false,
      yes: false,
    });

    // Must NOT be in harness/harness.md → would register as /harness:harness
    expect(fs.existsSync(path.join(tmpDir, 'harness', 'harness.md'))).toBe(false);
  });

  it('parent-level file contains the generated header', () => {
    const skillsDir = path.join(__dirname, 'fixtures', 'command-name-skill');
    generateSlashCommands({
      platforms: ['claude-code'],
      global: false,
      includeGlobal: false,
      skillsDir,
      output: tmpDir,
      dryRun: false,
      yes: false,
    });

    const content = fs.readFileSync(path.join(tmpDir, 'harness.md'), 'utf-8');
    expect(content).toContain('<!-- Generated by harness generate-slash-commands');
  });

  it('reports the parent-level file in added results', () => {
    const skillsDir = path.join(__dirname, 'fixtures', 'command-name-skill');
    const results = generateSlashCommands({
      platforms: ['claude-code'],
      global: false,
      includeGlobal: false,
      skillsDir,
      output: tmpDir,
      dryRun: false,
      yes: false,
    });

    const claudeResult = results.find((r) => r.platform === 'claude-code');
    expect(claudeResult?.added).toContain('harness.md');
  });
});
