/**
 * Documentation discovery — walks the project's docs tree plus the root
 * README, EXCLUDING the surfaces owned by sibling craft skills:
 *   - `docs/knowledge/`  → knowledge-craft
 *   - `docs/changes/`, `docs/decisions/`, `docs/adr/` → spec-craft (proposals + ADRs)
 * and generated / non-teaching surfaces (roadmap shards, execution plans,
 * captured solution post-mortems) that are not prose a human authored to teach.
 *
 * Structural twin of harness-design-craft's component discovery and a direct
 * sibling of knowledge-craft's entry discovery.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { DocKind } from '../catalog/rubrics/types.js';

export const DOCS_ROOT = 'docs';

/**
 * Directory names under `docs/` that docs-craft never critiques. `knowledge`
 * and the ADR/proposal surfaces belong to sibling craft skills; the rest are
 * generated or non-teaching artifacts that would only add noise.
 */
export const DEFAULT_EXCLUDED_DIRS: ReadonlyArray<string> = [
  'knowledge', // knowledge-craft territory
  'changes', // spec-craft territory (proposals + plans)
  'decisions', // spec-craft territory (ADRs)
  'adr', // spec-craft territory (ADRs)
  'roadmap.d', // generated roadmap shards
  'plans', // execution plans (generated by planning)
  'solutions', // captured post-mortems (harness-compound)
  'blueprint', // generated blueprint artifacts
  'agent-setup', // generated agent-setup prompts
];

export interface DiscoveredDoc {
  /** Absolute path to the doc file. */
  file: string;
  /** Path relative to the project root (POSIX separators) for display. */
  relative: string;
  /** Coarse classification used to filter rubrics + shape the prompt. */
  kind: DocKind;
}

/**
 * Classify a doc by its relative path. Cheap heuristics only — the LLM does the
 * real judgment; this just filters obviously-inapplicable rubrics (e.g. the
 * API-response rubric should not fire on a narrative guide).
 */
export function classifyDoc(relative: string): DocKind {
  const lower = relative.toLowerCase();
  const base = path.basename(lower);
  if (base === 'readme.md') return 'readme';
  if (/(^|\/)(api|reference)(\/|$)/.test(lower) || lower.includes('reference')) return 'reference';
  if (/(^|\/)(guides?|tutorials?|getting-started|how-to)(\/|$)/.test(lower)) return 'guide';
  return 'prose';
}

export function discoverDocs(
  projectRoot: string,
  extraExcludeDirs?: ReadonlyArray<string>
): DiscoveredDoc[] {
  const exclude = new Set<string>([...DEFAULT_EXCLUDED_DIRS, ...(extraExcludeDirs ?? [])]);
  const out: DiscoveredDoc[] = [];
  const seen = new Set<string>();

  const docsRoot = path.join(projectRoot, DOCS_ROOT);
  if (fs.existsSync(docsRoot)) {
    walk(docsRoot, projectRoot, out, exclude, seen);
  }

  // Root README — the highest-traffic teaching doc in most repos, and it lives
  // outside docs/, so it needs an explicit include.
  const rootReadme = path.join(projectRoot, 'README.md');
  if (fs.existsSync(rootReadme) && !seen.has(rootReadme)) {
    out.push({ file: rootReadme, relative: 'README.md', kind: 'readme' });
    seen.add(rootReadme);
  }

  return out;
}

function walk(
  dir: string,
  projectRoot: string,
  out: DiscoveredDoc[],
  exclude: Set<string>,
  seen: Set<string>
): void {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (exclude.has(entry.name)) continue;
      walk(full, projectRoot, out, exclude, seen);
      continue;
    }
    if (!entry.isFile()) continue;
    if (!entry.name.toLowerCase().endsWith('.md')) continue;
    if (seen.has(full)) continue;
    const relative = path.relative(projectRoot, full).replaceAll('\\', '/');
    out.push({ file: full, relative, kind: classifyDoc(relative) });
    seen.add(full);
  }
}
