/**
 * Roadmap aggregate-drift doctor (Phase 6, roadmap shard store).
 *
 * In sharded mode the per-row shards under `docs/roadmap.d/` are canonical and the
 * roadmap aggregate file is a GENERATED `merge=ours` view. The aggregate is
 * regenerated by a local husky hook on commit/merge — but local hooks are
 * per-developer, bypassable, and invisible to CI. This pure helper backs a
 * CI-checkable freshness contract: `harness validate` compares the committed
 * aggregate against a fresh regeneration of the shards and warns when they have
 * drifted, so a stale aggregate is caught in the pipeline rather than at read time.
 * The documented fix is `harness roadmap regen`.
 *
 * This module is pure (the merge-driver doctor pattern): callers do the I/O —
 * detect the shard dir, regenerate from the shards, and read the committed
 * aggregate — then pass the strings here. Drift is never an error; a stale
 * aggregate is cosmetic (correctness reads the shards, invariant R), so this only
 * ever yields a warning.
 */

/** Inputs to {@link checkRoadmapAggregateDrift}. */
export interface RoadmapAggregateDriftInput {
  /** Whether `docs/roadmap.d/` is present — i.e. the project is sharded. */
  shardDirExists: boolean;
  /** The committed aggregate content, or `null` when the aggregate file is absent. */
  committedAggregate: string | null;
  /**
   * The aggregate freshly regenerated from the shards, or `null` when regeneration
   * was not possible (e.g. unreadable/malformed shards) — in which case the check
   * is not applicable and other validation surfaces the underlying problem.
   */
  regeneratedAggregate: string | null;
}

/** Result of {@link checkRoadmapAggregateDrift}. */
export interface RoadmapAggregateDriftResult {
  /** True only when the project is sharded AND a comparison was possible. */
  applicable: boolean;
  /** True when {@link applicable} and the committed aggregate differs from the regenerated one. */
  stale: boolean;
}

/** Normalize line endings so a CRLF-vs-LF-only difference is not treated as drift. */
function normalizeEol(content: string): string {
  return content.replace(/\r\n/g, '\n');
}

/**
 * Decide whether a project's committed roadmap aggregate is stale relative to its
 * shards. Returns `{ applicable: false, stale: false }` (a no-op) for monolith
 * projects (no shard dir) and when regeneration was not possible. Otherwise reports
 * `stale: true` when the committed aggregate (treated as empty when absent) differs
 * from the regenerated aggregate after line-ending normalization.
 *
 * The comparison normalizes CRLF→LF on both sides first: regeneration always emits
 * LF, but a Windows clone with `core.autocrlf=true` (and no `.gitattributes eol=lf`
 * for the file) reads the committed aggregate back as CRLF, which would otherwise
 * surface a spurious drift warning on an otherwise-fresh aggregate.
 */
export function checkRoadmapAggregateDrift(
  input: RoadmapAggregateDriftInput
): RoadmapAggregateDriftResult {
  if (!input.shardDirExists || input.regeneratedAggregate === null) {
    return { applicable: false, stale: false };
  }
  const committed = normalizeEol(input.committedAggregate ?? '');
  const regenerated = normalizeEol(input.regeneratedAggregate);
  return { applicable: true, stale: committed !== regenerated };
}
