export type Platform = 'claude-code' | 'gemini-cli';

export const VALID_PLATFORMS: Platform[] = ['claude-code', 'gemini-cli'];

export interface SkillArg {
  name: string;
  description: string;
  required: boolean;
}

export interface SlashCommandSpec {
  name: string;
  namespace: string;
  fullName: string;
  description: string;
  version: string;
  cognitiveMode?: string;
  tools: string[];
  args: SkillArg[];
  skillYamlName: string;
  sourceDir: string;

  prompt: {
    context: string;
    objective: string;
    executionContext: string;
    process: string;
  };
}

export interface GenerateOptions {
  platforms: Platform[];
  global: boolean;
  output?: string;
  skillsDir: string;
  dryRun: boolean;
  yes: boolean;
}

export const GENERATED_HEADER_CLAUDE = '<!-- Generated by harness generate-slash-commands. Do not edit. -->';
export const GENERATED_HEADER_GEMINI = '# Generated by harness generate-slash-commands. Do not edit.';
