// src/rules/index.ts
//
// AUTO-GENERATED by scripts/generate-rules-barrel.mjs — DO NOT EDIT BY HAND.
// Add a rule file to src/rules/ and it is registered automatically; run
// `pnpm generate:rules` (or any build/test) to refresh this file.
import enforceDocExports from './enforce-doc-exports';
import noCircularDeps from './no-circular-deps';
import noDisabledTests from './no-disabled-tests';
import noEmptyDescribe from './no-empty-describe';
import noFocusedTests from './no-focused-tests';
import noForbiddenImports from './no-forbidden-imports';
import noHardcodedPathSeparator from './no-hardcoded-path-separator';
import noHardcodedTestCount from './no-hardcoded-test-count';
import noLayerViolation from './no-layer-violation';
import noNestedLoopsInCritical from './no-nested-loops-in-critical';
import noProcessEnvInSpawn from './no-process-env-in-spawn';
import noSkippedTests from './no-skipped-tests';
import noSpreadInVariadic from './no-spread-in-variadic';
import noSyncIoInAsync from './no-sync-io-in-async';
import noUnboundedArrayChains from './no-unbounded-array-chains';
import noUndefinedOptionalAssignment from './no-undefined-optional-assignment';
import noUnixShellCommand from './no-unix-shell-command';
import requireBoundarySchema from './require-boundary-schema';
import requirePathNormalization from './require-path-normalization';
import type { TSESLint } from '@typescript-eslint/utils';

// Explicit annotation so the exported type is nameable via the direct
// @typescript-eslint/utils dependency rather than the hoisted .pnpm path
// (avoids TS2742 in downstream DTS builds).
export const rules: Record<string, TSESLint.RuleModule<string, unknown[]>> = {
  'enforce-doc-exports': enforceDocExports,
  'no-circular-deps': noCircularDeps,
  'no-disabled-tests': noDisabledTests,
  'no-empty-describe': noEmptyDescribe,
  'no-focused-tests': noFocusedTests,
  'no-forbidden-imports': noForbiddenImports,
  'no-hardcoded-path-separator': noHardcodedPathSeparator,
  'no-hardcoded-test-count': noHardcodedTestCount,
  'no-layer-violation': noLayerViolation,
  'no-nested-loops-in-critical': noNestedLoopsInCritical,
  'no-process-env-in-spawn': noProcessEnvInSpawn,
  'no-skipped-tests': noSkippedTests,
  'no-spread-in-variadic': noSpreadInVariadic,
  'no-sync-io-in-async': noSyncIoInAsync,
  'no-unbounded-array-chains': noUnboundedArrayChains,
  'no-undefined-optional-assignment': noUndefinedOptionalAssignment,
  'no-unix-shell-command': noUnixShellCommand,
  'require-boundary-schema': requireBoundarySchema,
  'require-path-normalization': requirePathNormalization,
};
