import type { SecurityRule } from '../types';

export const secretRules: SecurityRule[] = [
  {
    id: 'SEC-SEC-001',
    name: 'AWS Access Key',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/(?:AKIA|ABIA|ACCA|ASIA)[0-9A-Z]{16}/],
    message: 'Hardcoded AWS access key detected',
    remediation: 'Use environment variables or a secrets manager',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-002',
    name: 'Generic API Key/Secret Assignment',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [
      /(?:api[_-]?key|api[_-]?secret|secret[_-]?key|access[_-]?token|auth[_-]?token)\s*[:=]\s*['"][^'"]{8,}['"]/i,
    ],
    message: 'Hardcoded API key or secret detected',
    remediation: 'Use environment variables: process.env.API_KEY',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-003',
    name: 'Private Key',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/-----BEGIN\s(?:RSA|DSA|EC|OPENSSH|PGP)\s(?:PRIVATE\s)?KEY-----/],
    message: 'Private key detected in source code',
    remediation: 'Store private keys in a secrets manager, never in source',
    references: ['CWE-321'],
  },
  {
    id: 'SEC-SEC-004',
    name: 'Password Assignment',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/(?:password|passwd|pwd)\s*[:=]\s*['"][^'"]{4,}['"]/i],
    message: 'Hardcoded password detected',
    remediation: 'Use environment variables or a secrets manager',
    references: ['CWE-259'],
  },
  {
    id: 'SEC-SEC-005',
    name: 'JWT/Bearer Token',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/],
    message: 'Hardcoded JWT token detected',
    remediation: 'Tokens should be fetched at runtime, not embedded in source',
    references: ['CWE-798'],
  },
];
