import type { SecurityRule } from '../types';

export const secretRules: SecurityRule[] = [
  {
    id: 'SEC-SEC-001',
    name: 'AWS Access Key',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/(?:AKIA|ABIA|ACCA|ASIA)[0-9A-Z]{16}/],
    message: 'Hardcoded AWS access key detected',
    remediation: 'Use environment variables or a secrets manager',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-002',
    name: 'Generic API Key/Secret Assignment',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [
      /(?:api[_-]?key|api[_-]?secret|secret[_-]?key|access[_-]?token|auth[_-]?token)\s*[:=]\s*['"][^'"]{8,}['"]/i,
    ],
    message: 'Hardcoded API key or secret detected',
    remediation: 'Use environment variables: process.env.API_KEY',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-003',
    name: 'Private Key',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/-----BEGIN\s(?:RSA|DSA|EC|OPENSSH|PGP)\s(?:PRIVATE\s)?KEY-----/],
    message: 'Private key detected in source code',
    remediation: 'Store private keys in a secrets manager, never in source',
    references: ['CWE-321'],
  },
  {
    id: 'SEC-SEC-004',
    name: 'Password Assignment',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/(?:password|passwd|pwd)\s*[:=]\s*['"][^'"]{4,}['"]/i],
    message: 'Hardcoded password detected',
    remediation: 'Use environment variables or a secrets manager',
    references: ['CWE-259'],
  },
  {
    id: 'SEC-SEC-005',
    name: 'JWT/Bearer Token',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/],
    message: 'Hardcoded JWT token detected',
    remediation: 'Tokens should be fetched at runtime, not embedded in source',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-006',
    name: 'Anthropic API Key',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/sk-ant-api\d{2}-[A-Za-z0-9_-]{20,}/],
    message: 'Hardcoded Anthropic API key detected',
    remediation: 'Use environment variables: process.env.ANTHROPIC_API_KEY',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-007',
    name: 'OpenAI API Key',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/sk-proj-[A-Za-z0-9_-]{20,}/],
    message: 'Hardcoded OpenAI API key detected',
    remediation: 'Use environment variables: process.env.OPENAI_API_KEY',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-008',
    name: 'Google API Key',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/AIza[A-Za-z0-9_-]{35}/],
    message: 'Hardcoded Google API key detected',
    remediation: 'Use environment variables or a secrets manager for Google API keys',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-009',
    name: 'GitHub Personal Access Token',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/gh[pous]_[A-Za-z0-9_]{36,}/],
    message: 'Hardcoded GitHub personal access token detected',
    remediation: 'Use environment variables: process.env.GITHUB_TOKEN',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-010',
    name: 'Stripe Live Key',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/\b[spr]k_live_[A-Za-z0-9]{24,}/],
    message: 'Hardcoded Stripe live key detected',
    remediation: 'Use environment variables for Stripe keys; never commit live keys',
    references: ['CWE-798'],
  },
  {
    id: 'SEC-SEC-011',
    name: 'Database Connection String with Credentials',
    category: 'secrets',
    severity: 'error',
    confidence: 'high',
    patterns: [/(?:postgres|mysql|mongodb|redis|amqp|mssql)(?:\+\w+)?:\/\/[^/\s:]+:[^@/\s]+@/i],
    message: 'Database connection string with embedded credentials detected',
    remediation: 'Use environment variables for connection strings; separate credentials from URIs',
    references: ['CWE-798'],
  },
];
