import { describe, it, expect } from 'vitest';
import { renderGeminiAgent } from '../../src/agent-definitions/render-gemini-cli';
import type { AgentDefinition } from '../../src/agent-definitions/generator';

const mockDef: AgentDefinition = {
  name: 'harness-code-reviewer',
  description: 'Perform code review and address findings.',
  tools: ['Bash', 'Read', 'Glob', 'Grep'],
  role: 'Perform AI-powered code review',
  skills: ['harness-code-review'],
  steps: [
    { command: 'validate', when: 'always' },
    { skill: 'harness-code-review', when: 'on_pr', output: 'auto' },
  ],
  methodology: '# Code Review\n\nFull methodology here.',
};

describe('renderGeminiAgent', () => {
  it('produces markdown with YAML frontmatter', () => {
    const output = renderGeminiAgent(mockDef);
    expect(output).toMatch(/^---\n/);
    expect(output).toContain('name: harness-code-reviewer');
    expect(output).toContain('description:');
  });

  it('includes generated header', () => {
    const output = renderGeminiAgent(mockDef);
    expect(output).toContain('Generated by harness generate-agent-definitions');
  });

  it('includes methodology content', () => {
    const output = renderGeminiAgent(mockDef);
    expect(output).toContain('Full methodology here');
  });

  it('renders tools as YAML array with Gemini CLI tool names', () => {
    const output = renderGeminiAgent(mockDef);
    expect(output).toContain(
      'tools:\n  - run_shell_command\n  - read_file\n  - glob\n  - search_file_content'
    );
  });

  it('maps all Claude Code tool names to Gemini equivalents', () => {
    const def = {
      ...mockDef,
      tools: ['Bash', 'Read', 'Write', 'Edit', 'Glob', 'Grep'],
    };
    const output = renderGeminiAgent(def);
    expect(output).toContain('run_shell_command');
    expect(output).toContain('read_file');
    expect(output).toContain('write_file');
    expect(output).toContain('replace');
    expect(output).toContain('glob');
    expect(output).toContain('search_file_content');
    expect(output).not.toContain('- Bash');
    expect(output).not.toContain('- Read');
    expect(output).not.toContain('- Write');
    expect(output).not.toContain('- Edit');
    expect(output).not.toContain('- Grep');
  });

  it('omits tools key when tools array is empty', () => {
    const def = { ...mockDef, tools: [] as string[] };
    const output = renderGeminiAgent(def);
    expect(output).not.toContain('tools:');
  });

  it('includes formatted steps', () => {
    const output = renderGeminiAgent(mockDef);
    expect(output).toContain('1. Run `harness validate` (always)');
    expect(output).toContain('2. Execute harness-code-review skill (on_pr)');
  });
});
