import { describe, it, expect } from 'vitest';
import { renderCodexAgent } from '../../src/agent-definitions/render-codex';
import type { AgentDefinition } from '../../src/agent-definitions/generator';

const baseDef: AgentDefinition = {
  name: 'harness-code-reviewer',
  description: 'Perform code review using harness methodology.',
  tools: ['Bash', 'Read', 'Write', 'Edit', 'Glob', 'Grep'],
  role: 'You are a senior code reviewer.',
  skills: ['harness-code-review', 'harness-verification'],
  steps: [
    { command: 'review-changes', when: 'always' },
    { skill: 'harness-verification', when: 'after-review' },
  ],
  methodology: 'Use the harness review process.',
};

describe('renderCodexAgent', () => {
  it('renders TOML with the three required Codex agent fields', () => {
    const out = renderCodexAgent(baseDef);
    expect(out).toMatch(/^# <!-- Generated by harness generate-agent-definitions/);
    expect(out).toContain('name = "harness-code-reviewer"');
    expect(out).toContain('description = "Perform code review using harness methodology."');
    expect(out).toMatch(/developer_instructions = """/);
  });

  it('embeds role, skills, and methodology inside developer_instructions', () => {
    const out = renderCodexAgent(baseDef);
    const instructionsMatch = out.match(/developer_instructions = """\n([\s\S]*?)\n"""/);
    expect(instructionsMatch).not.toBeNull();
    const body = instructionsMatch![1];
    expect(body).toContain('You are a senior code reviewer.');
    expect(body).toContain('harness-code-review');
    expect(body).toContain('Use the harness review process.');
  });

  it('escapes triple-quote sequences inside the instructions body to keep TOML parseable', () => {
    const def = { ...baseDef, methodology: 'Refer to """code blocks""" carefully.' };
    const out = renderCodexAgent(def);
    expect(out).not.toMatch(/"""[\s\S]*?""".*?""".*?"""/);
    expect(out).toContain('\\"\\"\\"code blocks\\"\\"\\"');
  });

  it('escapes backslashes and double quotes in the description', () => {
    const def = { ...baseDef, description: 'Has "quotes" and a \\ backslash' };
    const out = renderCodexAgent(def);
    expect(out).toContain('description = "Has \\"quotes\\" and a \\\\ backslash"');
  });

  it('includes harness generated-header so orphan detection finds the file', () => {
    const out = renderCodexAgent(baseDef);
    expect(out).toContain('Generated by harness generate-agent-definitions');
  });

  it('emits the description on a single line even when given multi-line input', () => {
    const def = { ...baseDef, description: 'Line one.\nLine two.' };
    const out = renderCodexAgent(def);
    const descLine = out.split('\n').find((l) => l.startsWith('description = '));
    expect(descLine).toBeDefined();
    expect(descLine).toContain('Line one.');
    expect(descLine).toContain('Line two.');
    expect(descLine).not.toContain('\n');
  });
});
