import { describe, it, expect } from 'vitest';
import { renderCursorAgent } from '../../src/agent-definitions/render-cursor';
import type { AgentDefinition } from '../../src/agent-definitions/generator';

const mockDef: AgentDefinition = {
  name: 'harness-code-reviewer',
  description: 'Perform code review and address findings.',
  tools: ['Bash', 'Read', 'Glob', 'Grep'],
  role: 'Perform AI-powered code review',
  skills: ['harness-code-review'],
  steps: [
    { command: 'validate', when: 'always' },
    { skill: 'harness-code-review', when: 'on_pr', output: 'auto' },
  ],
  methodology: '# Code Review\n\nFull methodology here.',
};

describe('renderCursorAgent', () => {
  it('produces markdown with YAML frontmatter (name + description, no tools)', () => {
    const output = renderCursorAgent(mockDef);
    expect(output).toMatch(/^---\n/);
    expect(output).toContain('name: harness-code-reviewer');
    expect(output).toContain('description:');
    // Cursor's plugin agent format does not include a `tools` field —
    // Cursor controls tool availability via its own permission model.
    expect(output).not.toContain('tools:');
  });

  it('includes generated header', () => {
    const output = renderCursorAgent(mockDef);
    expect(output).toContain('Generated by harness generate-agent-definitions');
  });

  it('includes role, skills, steps, methodology sections', () => {
    const output = renderCursorAgent(mockDef);
    expect(output).toContain('## Role');
    expect(output).toContain('AI-powered code review');
    expect(output).toContain('## Skills');
    expect(output).toContain('- harness-code-review');
    expect(output).toContain('## Steps');
    expect(output).toContain('1. Run `harness validate` (always)');
    expect(output).toContain('2. Execute harness-code-review skill (on_pr)');
    expect(output).toContain('## Methodology');
    expect(output).toContain('Full methodology here');
  });

  it('omits methodology section when empty', () => {
    const def = { ...mockDef, methodology: '' };
    const output = renderCursorAgent(def);
    expect(output).not.toContain('## Methodology');
  });

  it('handles unknown step types gracefully', () => {
    const def = {
      ...mockDef,
      steps: [{ unknown: 'value' } as unknown as AgentDefinition['steps'][number]],
    };
    const output = renderCursorAgent(def);
    expect(output).toContain('1. Unknown step');
  });
});
