import type { CICheckReport, CICheckResult, GateMeasurement } from '@harness-engineering/types';
import { accumulateLoss, computeGateLosses } from '../gate-loss';

const STATUS_ICONS: Record<string, string> = {
  pass: '\u2705',
  fail: '\u274C',
  warn: '\u26A0\uFE0F',
  skip: '\u23ED\uFE0F',
};

function statusIcon(status: string): string {
  return STATUS_ICONS[status] ?? status;
}

function formatCheckRow(check: CICheckResult): string {
  const icon = statusIcon(check.status);
  const issueCount = check.issues.length;
  return `| ${icon} ${check.name} | ${check.status} | ${issueCount} | ${check.durationMs}ms |`;
}

function formatIssueDetails(checks: CICheckResult[]): string {
  const checksWithIssues = checks.filter((c) => c.issues.length > 0);
  if (checksWithIssues.length === 0) return '';

  const sections: string[] = ['', '### Details', ''];
  for (const check of checksWithIssues) {
    sections.push(`**${check.name}:**`);
    for (const issue of check.issues) {
      const prefix = issue.severity === 'error' ? '\u274C' : '\u26A0\uFE0F';
      const location = issue.file
        ? issue.line
          ? ` (\`${issue.file}:${issue.line}\`)`
          : ` (\`${issue.file}\`)`
        : '';
      sections.push(`- ${prefix} ${issue.message}${location}`);
    }
    sections.push('');
  }
  return sections.join('\n');
}

/**
 * Render the continuous-loss panel beside the pass/fail views (Taguchi
 * continuous-loss, #1673). Emission only: this reads the `measurements` each
 * thresholded check emitted alongside its verdict and shows the distance-to-limit
 * the binary status discards. Returns '' when no check took any measurement, so
 * reports without thresholded metrics are unchanged.
 */
function formatLossPanel(checks: CICheckResult[]): string {
  const measurements: GateMeasurement[] = checks.flatMap((c) => c.measurements ?? []);
  if (measurements.length === 0) return '';

  const losses = computeGateLosses(measurements);
  const accumulated = accumulateLoss(losses);

  const sections: string[] = [
    '',
    '### Continuous loss (distance-to-threshold)',
    '',
    `Accumulated loss **${accumulated.totalLoss.toFixed(3)}** across **${accumulated.count}** measurement(s), mean **${accumulated.meanLoss.toFixed(3)}**. Loss is low while comfortably passing and rises quadratically toward each threshold — a leading indicator the pass/fail verdict discards.`,
    '',
    '| Gate | Measured | Target | Margin | Loss |',
    '|------|----------|--------|--------|------|',
  ];
  for (const l of losses) {
    const unit = l.unit ?? '';
    const marginSign = l.margin >= 0 ? '+' : '';
    sections.push(
      `| ${l.gate} | ${l.measured}${unit} | ${l.target}${unit} | ${marginSign}${l.margin}${unit} | ${l.loss.toFixed(3)} |`
    );
  }
  sections.push('');
  return sections.join('\n');
}

/**
 * Format a CI check report as GitHub-flavored markdown.
 * Produces a summary table with per-check status, issue counts,
 * and detailed issue listings for checks that have findings.
 */
export function formatCIReportAsMarkdown(report: CICheckReport): string {
  const { summary, checks } = report;

  const header =
    report.exitCode === 0
      ? '## \u2705 Harness CI — All Checks Passed'
      : '## \u274C Harness CI — Checks Failed';

  const summaryLine = `**${summary.passed}** passed, **${summary.failed}** failed, **${summary.warnings}** warnings, **${summary.skipped}** skipped`;

  const table = [
    '',
    '| Check | Status | Issues | Duration |',
    '|-------|--------|--------|----------|',
    ...checks.map(formatCheckRow),
    '',
  ].join('\n');

  const details = formatIssueDetails(checks);
  const lossPanel = formatLossPanel(checks);

  const footer = `\n---\n*Generated by [harness ci notify](https://github.com/Intense-Visions/harness-engineering) at ${report.timestamp}*`;

  return [header, '', summaryLine, table, details, lossPanel, footer].join('\n');
}
