export { resolveConsent, readIdentity } from './consent';
export { getOrCreateInstallId } from './install-id';
export { collectEvents } from './collector';
export { send } from './transport';
export { CacheMetricsRecorder } from './cache-metrics';
export type { CacheMetricsRecorderOptions } from './cache-metrics';
export { OTLPExporter } from './exporter/otlp-http';
export type { OTLPExporterOptions } from './exporter/otlp-http';
export { SpanKind } from './exporter/types';
export type { SpanAttributes, TraceSpan } from './exporter/types';
