import { describe, it, expect } from 'vitest';
import {
  renderCodexSkill,
  renderCodexOpenaiYaml,
  renderCodexAgentsMd,
} from '../../src/slash-commands/render-codex';
import type { SlashCommandSpec } from '../../src/slash-commands/types';

const baseSpec: SlashCommandSpec = {
  name: 'brainstorming',
  namespace: 'harness',
  fullName: 'harness:brainstorming',
  description: 'Structured ideation and exploration with harness methodology',
  version: '1.0.0',
  cognitiveMode: 'constructive-architect',
  tools: ['Read', 'Write', 'Bash'],
  args: [{ name: 'path', description: 'Project path', required: false }],
  skillYamlName: 'harness-brainstorming',
  sourceDir: 'harness-brainstorming',
  skillsBaseDir: 'agents/skills/claude-code',
  prompt: {
    context: 'Cognitive mode: constructive-architect\nType: rigid',
    objective: 'Structured ideation and exploration',
    executionContext: '@agents/skills/claude-code/harness-brainstorming/SKILL.md',
    process: '1. Read SKILL.md and follow its workflow directly',
  },
};

const skillMdContent = '# Harness Brainstorming\n\nExplore ideas systematically.';

describe('renderCodexSkill', () => {
  it('returns the SKILL.md content with generated header prepended', () => {
    const output = renderCodexSkill(skillMdContent);
    expect(output).toContain('# Harness Brainstorming');
    expect(output).toContain('Explore ideas systematically.');
    expect(output).toContain('Generated by harness generate-slash-commands');
  });
});

describe('renderCodexOpenaiYaml', () => {
  it('returns a YAML placeholder with name and version fields', () => {
    const output = renderCodexOpenaiYaml(baseSpec);
    expect(output).toContain('name: harness-brainstorming');
    expect(output).toContain('version: "1.0.0"');
  });

  it('includes the reserved-for-phase-b comment', () => {
    const output = renderCodexOpenaiYaml(baseSpec);
    expect(output).toContain('Reserved for Phase B');
  });
});

describe('renderCodexAgentsMd', () => {
  const specs = [
    baseSpec,
    {
      ...baseSpec,
      name: 'execution',
      skillYamlName: 'harness-execution',
      description: 'Execute plans',
    },
  ];

  it('includes a heading and intro paragraph', () => {
    const output = renderCodexAgentsMd(specs);
    expect(output).toContain('# Harness Skills');
  });

  it('lists all skill names', () => {
    const output = renderCodexAgentsMd(specs);
    expect(output).toContain('harness-brainstorming');
    expect(output).toContain('harness-execution');
  });

  it('includes skill descriptions', () => {
    const output = renderCodexAgentsMd(specs);
    expect(output).toContain('Structured ideation and exploration with harness methodology');
    expect(output).toContain('Execute plans');
  });

  it('includes the generated header', () => {
    const output = renderCodexAgentsMd(specs);
    expect(output).toContain('Generated by harness generate-slash-commands');
  });
});
