import { describe, it, expect } from 'vitest';
import { renderCodexPrompt } from '../../src/slash-commands/render-codex-prompt';
import type { SlashCommandSpec } from '../../src/slash-commands/types';

const baseSpec: SlashCommandSpec = {
  name: 'debugging',
  namespace: 'harness',
  fullName: 'harness:debugging',
  description: 'Systematic debugging with harness validation and state tracking',
  version: '1.0.0',
  tools: [],
  args: [{ name: 'path', description: 'Project path', required: false }],
  skillYamlName: 'harness-debugging',
  sourceDir: 'harness-debugging',
  skillsBaseDir: 'agents/skills/claude-code',
  prompt: {
    context: 'ctx',
    objective: 'obj',
    executionContext: '@x',
    process: '1',
  },
};

describe('renderCodexPrompt', () => {
  it('emits YAML frontmatter with description and argument-hint', () => {
    const out = renderCodexPrompt(baseSpec);
    expect(out.startsWith('---\n')).toBe(true);
    expect(out).toContain(
      'description: Systematic debugging with harness validation and state tracking'
    );
    expect(out).toContain('argument-hint: "[path]"'); // leading [ forces quoting
  });

  it('inserts a body that delegates to the harness skill', () => {
    const out = renderCodexPrompt(baseSpec);
    expect(out).toMatch(/Use the `harness-debugging` skill/);
    expect(out).toContain('~/.codex/skills/harness-debugging/SKILL.md');
  });

  it('includes $ARGUMENTS so user input is forwarded to the model', () => {
    const out = renderCodexPrompt(baseSpec);
    expect(out).toContain('$ARGUMENTS');
  });

  it('quotes description with a colon to keep YAML parseable', () => {
    const spec = { ...baseSpec, description: 'Phase 1: Investigate' };
    const out = renderCodexPrompt(spec);
    expect(out).toContain('description: "Phase 1: Investigate"');
  });

  it('omits argument-hint when the skill has no args', () => {
    const spec = { ...baseSpec, args: [] };
    const out = renderCodexPrompt(spec);
    expect(out).not.toContain('argument-hint:');
  });

  it('renders required args with angle brackets and optional with square', () => {
    const spec = {
      ...baseSpec,
      args: [
        { name: 'path', description: 'p', required: true },
        { name: 'flag', description: 'f', required: false },
      ],
    };
    const out = renderCodexPrompt(spec);
    expect(out).toContain('argument-hint: <path> [flag]'); // starts with < — valid unquoted YAML
  });

  it('includes generated-header so orphan detection can find it later', () => {
    const out = renderCodexPrompt(baseSpec);
    expect(out).toContain('Generated by harness generate-slash-commands');
  });
});
