import { Command } from 'commander';
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { Result, CICheckName, CIPlatform } from '@harness-engineering/core';
import { Ok, Err } from '@harness-engineering/core';
import { logger } from '../../output/logger';
import { CLIError, ExitCode } from '../../utils/errors';

const ALL_CHECKS: CICheckName[] = [
  'validate',
  'deps',
  'docs',
  'entropy',
  'security',
  'perf',
  'phase-gate',
  'arch',
];

interface GenerateResult {
  filename: string;
  content: string;
}

function buildSkipFlag(checks?: CICheckName[]): string {
  if (!checks) return '';
  const skipChecks = ALL_CHECKS.filter((c) => !checks.includes(c));
  if (skipChecks.length === 0) return '';
  return ` --skip ${skipChecks.join(',')}`;
}

function generateGitHubActions(skipFlag: string): string {
  return `name: Harness Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: harness-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  harness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install -g @harness-engineering/cli
      - name: Run harness checks
        run: harness ci check --json${skipFlag}
`;
}

function generateGitLabCI(skipFlag: string): string {
  return `harness:
  stage: test
  image: node:22
  before_script:
    - npm install -g @harness-engineering/cli
  script:
    - harness ci check --json${skipFlag}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
`;
}

function generateGenericScript(skipFlag: string): string {
  return `#!/usr/bin/env bash
set -euo pipefail

# Harness CI Check Script
# Generated by: harness ci init --platform generic

if ! command -v harness &> /dev/null; then
  echo "Installing @harness-engineering/cli..."
  npm install -g @harness-engineering/cli
fi

echo "Running harness checks..."
harness ci check --json${skipFlag}
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
  echo "All harness checks passed."
elif [ $EXIT_CODE -eq 1 ]; then
  echo "Harness checks failed. See report above."
else
  echo "Harness internal error."
fi

exit $EXIT_CODE
`;
}

export function generateCIConfig(options: {
  platform: CIPlatform;
  checks?: CICheckName[];
}): Result<GenerateResult, CLIError> {
  const { platform, checks } = options;
  const skipFlag = buildSkipFlag(checks);

  const generators: Record<CIPlatform, { filename: string; generate: (skip: string) => string }> = {
    github: { filename: '.github/workflows/harness.yml', generate: generateGitHubActions },
    gitlab: { filename: '.gitlab-ci-harness.yml', generate: generateGitLabCI },
    generic: { filename: 'harness-ci.sh', generate: generateGenericScript },
  };

  const entry = generators[platform];
  if (!entry) {
    return Err(new CLIError(`Unknown platform: ${platform}`, ExitCode.ERROR));
  }

  return Ok({
    filename: entry.filename,
    content: entry.generate(skipFlag),
  });
}

function detectPlatform(): CIPlatform | null {
  if (fs.existsSync('.github')) return 'github';
  if (fs.existsSync('.gitlab-ci.yml')) return 'gitlab';
  return null;
}

export function createInitCommand(): Command {
  return new Command('init')
    .description('Generate CI configuration for harness checks')
    .option('--platform <platform>', 'CI platform: github, gitlab, or generic')
    .option('--checks <list>', 'Comma-separated list of checks to include')
    .action(async (opts, cmd) => {
      const globalOpts = cmd.optsWithGlobals();
      const platform: CIPlatform = opts.platform ?? detectPlatform() ?? 'generic';

      const checks = opts.checks
        ? (opts.checks.split(',').map((s: string) => s.trim()) as CICheckName[])
        : undefined;

      const opts2: Parameters<typeof generateCIConfig>[0] = { platform };
      if (checks) opts2.checks = checks;
      const result = generateCIConfig(opts2);

      if (!result.ok) {
        logger.error(result.error.message);
        process.exit(result.error.exitCode);
      }

      const { filename, content } = result.value;
      const targetPath = path.resolve(filename);
      const dir = path.dirname(targetPath);

      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(targetPath, content);

      if (platform === 'generic' && process.platform !== 'win32') {
        fs.chmodSync(targetPath, '755');
      }

      if (globalOpts.json) {
        console.log(JSON.stringify({ file: filename, platform }));
      } else {
        logger.success(`Generated ${filename} for ${platform}`);
        logger.dim("Run 'harness ci check' to test locally");
      }
    });
}
